/**
 * Generate lib/client.js from the per-namespace dictionaries in src/locales/ (core
 * namespaces shipped by DSH) and src/locales/plugins/ (third-party plugin namespaces).
 *
 * Usage:
 *   node scripts/build.mjs           # write lib/client.js
 *   node scripts/build.mjs --check   # fail when lib/client.js is stale (CI)
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const coreDir = path.join(root, 'src/locales')
const pluginDir = path.join(root, 'src/locales/plugins')
const target = path.join(root, 'lib/client.js')
const check = process.argv.includes('--check')

export const LANGUAGE = Object.freeze({ id: 'ru', label: 'Русский', fallback: 'en' })
export const PACKAGE_NAME = 'dsh-locale-ru'

/** Read one dictionary directory, asserting that both sides are complete. */
function readDir(dir, dicts, pairs) {
  let keys = 0
  if (!fs.existsSync(dir)) return keys
  for (const file of fs.readdirSync(dir).filter((f) => f.endsWith('.json')).sort()) {
    const ns = file.slice(0, -5)
    const entries = JSON.parse(fs.readFileSync(path.join(dir, file), 'utf8'))
    const ru = {}
    for (const [key, value] of Object.entries(entries)) {
      if (typeof value?.en !== 'string' || typeof value?.ru !== 'string') {
        throw new Error(`${ns} / ${key}: expected { en, ru } strings`)
      }
      if (value.en === '' && value.ru !== '') {
        throw new Error(`${ns} / ${key}: the English source is empty, so the translation must be empty as well`)
      }
      ru[key] = value.ru
      keys++
    }
    dicts[ns] = ru
    pairs[ns] = entries
  }
  return keys
}

/**
 * Read every namespace dictionary, asserting that both sides are complete and that a
 * namespace is owned by exactly one directory: core namespaces live in `src/locales`,
 * third-party plugin namespaces in `src/locales/plugins`. A namespace in both places
 * would register the same `(namespace, locale)` pair twice, which the locale service
 * rejects.
 * @returns `{ dicts, pairs, keys, pluginDicts, pluginPairs, pluginKeys }`.
 */
export function readDictionaries() {
  const dicts = {}
  const pairs = {}
  const keys = readDir(coreDir, dicts, pairs, 'core')

  const pluginDicts = {}
  const pluginPairs = {}
  const pluginKeys = readDir(pluginDir, pluginDicts, pluginPairs, 'plugin')

  for (const ns of Object.keys(pluginDicts)) {
    if (ns in dicts) {
      throw new Error(`${ns}: namespace is declared as both a core and a plugin dictionary`)
    }
  }
  return { dicts, pairs, keys, pluginDicts, pluginPairs, pluginKeys }
}

/** Render the browser module the client module loader consumes. */
export function render({ dicts, keys, pluginDicts, pluginKeys }) {
  const body = (value) =>
    JSON.stringify(value, null, 2)
      .split('\n')
      .map((line) => '\t\t' + line)
      .join('\n')
  const namespaces = Object.keys(dicts).length
  const pluginNamespaces = Object.keys(pluginDicts).length
  return `/**
 * ${LANGUAGE.label} language pack for the DeepSeek Harness web GUI.
 * Generated by scripts/build.mjs from src/locales/ and src/locales/plugins/ — do not edit by hand.
 * ${namespaces} core namespaces, ${pluginNamespaces} plugin namespaces, ${keys + pluginKeys} strings.
 */
window.__ModuleLoader__.load({
\tid: '${PACKAGE_NAME}',
\tfactory(require) {
\t\tconst DICTS = ${body(dicts).trimStart()};

\t\tconst PLUGIN_DICTS = ${body(pluginDicts).trimStart()};

\t\treturn {
\t\t\tinject: ['locale'],
\t\t\tapply(ctx) {
\t\t\t\tctx.effect(
\t\t\t\t\t() => ctx.locale.addLanguage(${JSON.stringify(LANGUAGE)}),
\t\t\t\t\t'locale-ru: language',
\t\t\t\t);
\t\t\t\tfor (const [ns, dict] of Object.entries(DICTS)) {
\t\t\t\t\ttry {
\t\t\t\t\t\tctx.effect(() => ctx.locale.register(ns, '${LANGUAGE.id}', dict), 'locale-ru: ' + ns);
\t\t\t\t\t} catch (error) {
\t\t\t\t\t\tconsole.warn('locale-ru: cannot register namespace', ns, error);
\t\t\t\t\t}
\t\t\t\t}
\t\t\t\t// Third-party plugin namespaces register one task later. A plugin that ships its
\t\t\t\t// own ${LANGUAGE.id} dictionary owns its namespace: the service rejects a second
\t\t\t\t// registration for the same (namespace, locale) pair, so claiming the namespace
\t\t\t\t// first would break that plugin. Registering afterwards leaves its dictionary in
\t\t\t\t// place and only fills in the plugins that ship no ${LANGUAGE.id} copy at all.
\t\t\t\tctx.effect(() => {
\t\t\t\t\tconst disposers = [];
\t\t\t\t\tconst timer = setTimeout(() => {
\t\t\t\t\t\tfor (const [ns, dict] of Object.entries(PLUGIN_DICTS)) {
\t\t\t\t\t\t\ttry {
\t\t\t\t\t\t\t\tdisposers.push(ctx.locale.register(ns, '${LANGUAGE.id}', dict));
\t\t\t\t\t\t\t} catch (error) {
\t\t\t\t\t\t\t\tconsole.warn('locale-ru: plugin namespace', ns, 'is already covered', error);
\t\t\t\t\t\t\t}
\t\t\t\t\t\t}
\t\t\t\t\t}, 0);
\t\t\t\t\treturn () => {
\t\t\t\t\t\tclearTimeout(timer);
\t\t\t\t\t\tfor (const dispose of disposers) dispose();
\t\t\t\t\t};
\t\t\t\t}, 'locale-ru: plugin dictionaries');
\t\t\t\t// Select Russian once, on the first page load after installation. The flag
\t\t\t\t// hands the choice to the user afterwards: switching back to English in
\t\t\t\t// Settings → General → Language is never overridden again.
\t\t\t\ttry {
\t\t\t\t\tconst flag = 'locale-ru:auto-selected';
\t\t\t\t\tif (window.localStorage.getItem(flag) === null) {
\t\t\t\t\t\twindow.localStorage.setItem(flag, '1');
\t\t\t\t\t\tif (ctx.locale.getSnapshot().active !== '${LANGUAGE.id}') ctx.locale.setLocale('${LANGUAGE.id}');
\t\t\t\t\t}
\t\t\t\t} catch (error) {
\t\t\t\t\tconsole.warn('locale-ru: automatic selection skipped', error);
\t\t\t\t}
\t\t\t},
\t\t};
\t},
});
`
}

const isMain = process.argv[1] !== undefined && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)

if (isMain) {
  const dictionaries = readDictionaries()
  const { dicts, keys, pluginDicts, pluginKeys } = dictionaries
  const content = render(dictionaries)
  const summary = `${Object.keys(dicts).length} core + ${Object.keys(pluginDicts).length} plugin namespaces, ${keys + pluginKeys} strings`

  if (check) {
    const current = fs.existsSync(target) ? fs.readFileSync(target, 'utf8') : ''
    if (current !== content) {
      console.error('lib/client.js is stale: run `npm run build`')
      process.exit(1)
    }
    console.log(`lib/client.js is up to date: ${summary}`)
  } else {
    fs.mkdirSync(path.dirname(target), { recursive: true })
    fs.writeFileSync(target, content)
    console.log(`lib/client.js written: ${summary}, ${(content.length / 1024).toFixed(1)} KiB`)
  }
}
