/**
 * Generate lib/client.js from the per-namespace dictionaries in src/locales/.
 *
 * Usage:
 *   node scripts/build.mjs           # write lib/client.js
 *   node scripts/build.mjs --check   # fail when lib/client.js is stale (CI)
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const localesDir = path.join(root, 'src/locales')
const target = path.join(root, 'lib/client.js')
const check = process.argv.includes('--check')

export const LANGUAGE = Object.freeze({ id: 'ru', label: 'Русский', fallback: 'en' })
export const PACKAGE_NAME = 'dsh-locale-ru'

/** Read every namespace dictionary, asserting that both sides are complete. */
export function readDictionaries() {
  const dicts = {}
  const pairsByNamespace = {}
  let keys = 0
  for (const file of fs.readdirSync(localesDir).filter((f) => f.endsWith('.json')).sort()) {
    const ns = file.slice(0, -5)
    const pairs = JSON.parse(fs.readFileSync(path.join(localesDir, file), 'utf8'))
    const ru = {}
    for (const [key, value] of Object.entries(pairs)) {
      if (typeof value?.en !== 'string' || typeof value?.ru !== 'string') {
        throw new Error(`${ns} / ${key}: expected { en, ru } strings`)
      }
      if (value.en === '' && value.ru !== '') {
        throw new Error(`${ns} / ${key}: the English source is empty, so the translation must be empty as well`)
      }
      ru[key] = value.ru
      keys++
    }
    dicts[ns] = ru
    pairsByNamespace[ns] = pairs
  }
  return { dicts, pairs: pairsByNamespace, keys }
}

/** Render the browser module the client module loader consumes. */
export function render(dicts, keys) {
  const body = JSON.stringify(dicts, null, 2)
    .split('\n')
    .map((line) => '\t\t' + line)
    .join('\n')
  return `/**
 * ${LANGUAGE.label} language pack for the DeepSeek Harness web GUI.
 * Generated by scripts/build.mjs from src/locales/ — do not edit by hand.
 * ${Object.keys(dicts).length} namespaces, ${keys} strings.
 */
window.__ModuleLoader__.load({
\tid: '${PACKAGE_NAME}',
\tfactory(require) {
\t\tconst DICTS = ${body.trimStart()};

\t\treturn {
\t\t\tinject: ['locale'],
\t\t\tapply(ctx) {
\t\t\t\tctx.effect(
\t\t\t\t\t() => ctx.locale.addLanguage(${JSON.stringify(LANGUAGE)}),
\t\t\t\t\t'locale-ru: language',
\t\t\t\t);
\t\t\t\tfor (const [ns, dict] of Object.entries(DICTS)) {
\t\t\t\t\ttry {
\t\t\t\t\t\tctx.effect(() => ctx.locale.register(ns, '${LANGUAGE.id}', dict), 'locale-ru: ' + ns);
\t\t\t\t\t} catch (error) {
\t\t\t\t\t\tconsole.warn('locale-ru: cannot register namespace', ns, error);
\t\t\t\t\t}
\t\t\t\t}
\t\t\t\t// Select Russian once, on the first page load after installation. The flag
\t\t\t\t// hands the choice to the user afterwards: switching back to English in
\t\t\t\t// Settings → General → Language is never overridden again.
\t\t\t\ttry {
\t\t\t\t\tconst flag = 'locale-ru:auto-selected';
\t\t\t\t\tif (window.localStorage.getItem(flag) === null) {
\t\t\t\t\t\twindow.localStorage.setItem(flag, '1');
\t\t\t\t\t\tif (ctx.locale.getSnapshot().active !== '${LANGUAGE.id}') ctx.locale.setLocale('${LANGUAGE.id}');
\t\t\t\t\t}
\t\t\t\t} catch (error) {
\t\t\t\t\tconsole.warn('locale-ru: automatic selection skipped', error);
\t\t\t\t}
\t\t\t},
\t\t};
\t},
});
`
}

const isMain = process.argv[1] !== undefined && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)

if (isMain) {
  const { dicts, keys } = readDictionaries()
  const content = render(dicts, keys)

  if (check) {
    const current = fs.existsSync(target) ? fs.readFileSync(target, 'utf8') : ''
    if (current !== content) {
      console.error('lib/client.js is stale: run `npm run build`')
      process.exit(1)
    }
    console.log(`lib/client.js is up to date: ${Object.keys(dicts).length} namespaces, ${keys} strings`)
  } else {
    fs.mkdirSync(path.dirname(target), { recursive: true })
    fs.writeFileSync(target, content)
    console.log(`lib/client.js written: ${Object.keys(dicts).length} namespaces, ${keys} strings, ${(content.length / 1024).toFixed(1)} KiB`)
  }
}
